/*
 * generated by Xtext 2.26.0.M2
 */
package de.fhdo.lemma.data.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDataDslScopeProvider extends DelegatingScopeProvider {
}
